# Generated by Django 2.0.7 on 2018-07-11 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pizza',
            name='pizzaType',
            field=models.CharField(choices=[('Regular', 'Regular'), ('Scilian', 'Sicilian')], default='Regular', max_length=64),
        ),
        migrations.AlterField(
            model_name='pizza',
            name='size',
            field=models.CharField(choices=[('Small', 'Small'), ('Large', 'Large')], default='Small', max_length=64),
        ),
        migrations.AlterField(
            model_name='subs',
            name='size',
            field=models.CharField(choices=[('Small', 'Small'), ('Large', 'Large')], default='Small', max_length=2),
        ),
        migrations.AlterField(
            model_name='subs',
            name='subType',
            field=models.CharField(choices=[('Cheese', 'Cheese'), ('Italian', 'Italian')], default='Cheese', max_length=2),
        ),
    ]
