# Generated by Django 2.0.7 on 2018-07-11 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20180711_1528'),
    ]

    operations = [
        migrations.CreateModel(
            name='toppings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('toppings', models.CharField(choices=[('Pepperoni', 'Pepperoni'), ('Sausage', 'Sausage'), ('Mushrooms', 'Mushrooms')], max_length=64)),
                ('pizzas', models.ManyToManyField(blank=True, related_name='toppings', to='orders.pizza')),
            ],
        ),
    ]
