# Generated by Django 2.0.7 on 2018-07-11 18:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_toppings'),
    ]

    operations = [
        migrations.CreateModel(
            name='order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pizza_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pizza_orders', to='orders.pizza')),
                ('sub_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_orders', to='orders.subs')),
            ],
        ),
    ]
