# Generated by Django 2.0.7 on 2018-07-11 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_auto_20180711_1901'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='pizza_order',
        ),
        migrations.RemoveField(
            model_name='order',
            name='sub_order',
        ),
        migrations.AddField(
            model_name='order',
            name='orderType',
            field=models.CharField(choices=[('Regular', 'Regular'), ('Sicilian', 'Sicilian'), ('Sub', 'Sub'), ('Pasta', 'Pasta'), ('Salad', 'Salad'), ('Platter', 'Platter')], default='Regular', max_length=64),
        ),
        migrations.AddField(
            model_name='order',
            name='size',
            field=models.CharField(blank=True, choices=[('Small', 'Small'), ('Large', 'Large')], max_length=64),
        ),
        migrations.AddField(
            model_name='order',
            name='toppings',
            field=models.CharField(blank=True, choices=[('Pepperoni', 'Pepperoni'), ('Sausage', 'Sausage')], max_length=64),
        ),
    ]
