# Generated by Django 2.0.7 on 2018-07-12 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_auto_20180711_1956'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sub',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('Cheese', 'Cheese'), ('Italian', 'Italian')], default='Cheese', max_length=64)),
                ('size', models.CharField(choices=[('Small', 'Small'), ('Large', 'Large')], default='Small', max_length=64)),
            ],
        ),
        migrations.DeleteModel(
            name='order',
        ),
        migrations.DeleteModel(
            name='subs',
        ),
        migrations.RemoveField(
            model_name='toppings',
            name='pizzas',
        ),
        migrations.RemoveField(
            model_name='pizza',
            name='pizzaType',
        ),
        migrations.AddField(
            model_name='pizza',
            name='category',
            field=models.CharField(choices=[('Regular', 'Reular'), ('Sicilian', 'Sicilian')], default='Regular', max_length=64),
        ),
        migrations.DeleteModel(
            name='toppings',
        ),
    ]
